/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.List;

public class App {
    public static void main(String[] args) {
        ListZipper zipper = new ListZipper();
        List<Integer> list1 = List.of(1, 3, 5);
        List<Integer> list2 = List.of(2, 4, 6);

        List<Integer> zippedList = zipper.zip(list1, list2);

        System.out.println("Zipped List: " + zippedList);

        // Example usage with strings
        List<String> stringList1 = List.of("a", "c", "e");
        List<String> stringList2 = List.of("b", "d");
        
        List<String> zippedStringList = zipper.zip(stringList1, stringList2);

        System.out.println("Zipped String List: " + zippedStringList);
    }
}
